spring.application.name=backend_social
spring.datasource.url=jdbc:mysql://localhost:3306/social_commerce
spring.datasource.username=root
spring.datasource.password=Mora@2000

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

BITLY_TOKEN=d455b8f7b8ee2b1c15aefff4e977adabd8ee3375